- platform: ffmpeg
  name: Uppfart
  input: -rtsp_transport tcp -i !secret camera_uppfart_url
  extra_arguments: -pred 1
- platform: ffmpeg
  name: Baksidan
  input: -rtsp_transport tcp -i !secret camera_baksida_url
  extra_arguments: -pred 1
