# https://github.com/topics/home-assistant-config
homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 22
  unit_system: metric
  time_zone: !secret timezone
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

# Enables configuration UI
config:
recorder:
  db_url: !secret mysql_db
history: !include history.yaml
logbook: !include logbook.yaml
#logger: !include logger.yaml

#customizer:
#  custom_ui: local

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - !secret trusted_networks
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 2
  base_url: !secret base_url

google_assistant: !include google_assistant.yaml

updater:
  reporting: False

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1QC0EY-if00-port0
  debug:
mqtt:
  discovery: true
  discovery_prefix: homeassistant

sun:

notify: !include notify.yaml

# Text to speech
tts:
  - platform: google
    cache: true
    language: 'sv'

panel_iframe:
  router:
    title: 'Router trafik'
    url: !secret router_url
  plex:
    title: 'Plex'
    url: !secret plex_url

group: !include_dir_merge_named group/
automation: !include_dir_merge_list automation
sensor: !include_dir_merge_list sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
input_boolean: !include input/input_boolean.yaml
media_player: !include media_players.yaml
device_tracker: !include_dir_merge_list device_tracker

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
# Cameras
camera: !include camera.yaml

apcupsd:
  host: !secret apcupsd_ip

climate:
  platform: zwave
