#
#   Automation Templates
#
- platform: template
  sensors:
#    True when washer power level is below 3.4 watts, high threshold of resting state
#    Default state is true
    washer_pwrdn:
      value_template: "{{ states('sensor.washer_power') | int < 3.4 }}"

#    True when Dryer power level is above 8.4 watts, showing dryer is in operation (as opposed to just having the door open)
#    Default state is false
    dryer_pwrup:
      value_template: "{{ states('sensor.dryer_power') | int > 8.4 }}"

#    True when Dishwasher power level is above 10 watts, showing dishwasher is in operation
#    Default state is false
    dish_pwrup:
      value_template: "{{ states('sensor.dishwasher_power') | int > 4 }}"