- alias: "Temperatur upp morgon"
  hide_entity: false
  trigger:
    - platform: time
      at: '04:45:00'
  action:
    - service: climate.set_temperature
      data: 
        entity_id: climate.ir_heating_1
        temperature: 23
        target_temp_high: 25
        target_temp_low: 19