# https://community.home-assistant.io/t/intruder-alert/24084/31
# https://community.home-assistant.io/t/numeric-state/20739/2
- alias: "Send notification upon failed login attempt"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: persistent_notification
        service: create
  action:
    - service: notify.html5
      data_template:
        message: >-
          {% set message = trigger.event.data.service_data.message %}
          {% if 'login attempt' in message|lower %}
            {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
          {% else %}
            {{ message }}
          {% endif %}
    - service: notify.pushbullet
      data_template:
        message: >-
          {% set message = trigger.event.data.service_data.message %}
          {% if 'login attempt' in message|lower %}
            {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
          {% else %}
            {{ message }}
          {% endif %}
