- alias: Lights on at sunset (offset)
  hide_entity: True
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:15:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.koksfonster
      - light.vardagsrum
      - light.byran
      - light.uppfart
      - light.algots_fonsterlampa
      - light.iris_matta
      - light.bedroom
      - light.julbelysning_ute

- alias: 'turn_lights_off'
  trigger:
    platform: time
    at: '22:45:00'
  condition:
    - condition: state
      entity_id: device_tracker.roberts_h8_mac
      state: 'not_home'
  action:
#    delay: '{{ (range(0, 2)|random|int) }}:{{ (range(0, 59)|random|int) }}:00'
    service: script.turn_on
    entity_id: script.goodnight
