- alias: 'Battery Alert'
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '20:25:00'
  condition:
    condition: template
    value_template: "{% if states('sensor.low_battery') %}true{% endif %}"
  action:
    - service: notify.pushbullet
    #- service: persistent_notification.create
      data_template:
        title: Low Battery
        message: "{{ states('sensor.low_battery') }}"
        notification_id: low-battery-alert
