- alias: Radio P4 at 10 on Saturdays
  hide_entity: True
  trigger:
    platform: time
    #after: '21:58:00'
    at: '09:58:00'
  condition:
    - condition: time
      weekday:
      - sat
      #- wed
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: tts.google_say
      entity_id: media_player.whole_house
      data:
        message: 'Melodikrysset börjar om 2minuter!'
    - delay: '00:00:35'
    - service: media_player.play_media
      entity_id: media_player.whole_house
      data:
        media_content_id: "http://http-live.sr.se/p4gotland-mp3-192"
        media_content_type: "audio/mp3"
