- alias: 'Set Radio Volume'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
         {% if is_state("input_select.chromecast_radio", "Kök") %} media_player.kitchen
         {% elif is_state("input_select.chromecast_radio", "Badrum") %} media_player.bathroom
         {% elif is_state("input_select.chromecast_radio", "Korridoren") %} media_player.hallway_speaker
         {% elif is_state("input_select.chromecast_radio", "Hela Huset") %} media_player.whole_house
         {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'
