- alias: Smokesensor
  hide_entity: True
  trigger:
    platform: state
    entity_id:
      - sensor.smokeniskait_smoke
      - sensor.smokealgots_smoke
      - sensor.smokebedroom_smoke
      - sensor.smokelivingroom_smoke
      - sensor.smokekitchen_smoke
    to: '255'
  action:
    - service: notify.html5
      data_template:
        title: "Niska@Home! '{{ trigger.to_state.attributes.friendly_name }}'"
        message: >
          {{ trigger.to_state.state }} in the {{ trigger.to_state.attributes.friendly_name }}.

- alias: Watersensor
  hide_entity: True
  trigger:
    platform: state
    entity_id:
      - binary_sensor.watersensor_sensor
    to: 'on'
  action:
    - service: notify.html5
      data_template:
        title: "Niska@Home! '{{ trigger.to_state.attributes.friendly_name }}'"
        message: >
          {{ trigger.to_state.state }} in the {{ trigger.to_state.attributes.friendly_name }}.
