homeassistant:
#  customize:
#    alarm_control_panel.home_alarm:


alarm_control_panel:
  - platform: manual
    name: Home Alarm
    # code:
    pending_time: 0
    disarm_after_trigger: 'false'
    armed_away:
      pending_time: 0
    triggered:
      pending_time: 0

##################################################
## Automation
##################################################

automation:
  - alias: 'Alarm Arm Away'
    initial_state: 'on'
    trigger:
        - platform: state
          entity_id: sensor.robert
          to: 'Nix'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm
      - service: notify.pushbullet
        data_template:
          title: 'Alarm Armed Away'
          message: >
            '{{ trigger.to_state.last_changed }}'

  - alias: 'Alarm Arm Home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.persons
        to: 'home'
    condition:
      condition: template
      value_template: '{{ states.alarm_control_panel.home_alarm.state != armed_home}}'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.home_alarm
      - service: notify.pushbullet
        data_template:
          title: 'Alarm Armed Home'
          message: >
            '{{ trigger.to_state.last_changed }}'

#- alias: 'Alarm Arm Night'
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: input_select.day_mode
#    to: 'Night'
#  action:
#    - service: alarm_control_panel.alarm_arm_night
#      entity_id: alarm_control_panel.home_alarm

  - alias: 'Alarm Disarm'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.robert
        to: 'Japp'
      - platform: time
        at: '06:40:00'
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: notify.pushbullet
        data_template:
          title: 'Alarm Disarmed'
          message: >
            '{{ trigger.to_state.last_changed }}'

  - alias: 'Alarm Trigger While Armed Away'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.pirkitchen_alarm_level
        to: '255'
      - platform: state
        entity_id: sensor.smokeniskait_smoke
        to: '255'
      - platform: state
        entity_id: sensor.smokealgots_smoke
        to: '255'
      - platform: state
        entity_id: sensor.smokebedroom_smoke_
        to: '255'
      - platform: state
        entity_id: sensor.smokelivingroom_smoke
        to: '255'
      - platform: state
        entity_id: sensor.smokekitchen_smoke
        to: '255'
      - platform: state
        entity_id: sensor.multisensorbathroom_burglar
        to: '8'
      - platform: state
        entity_id: switch.vardagsrum_magnetkontakt
        to: 'on'
      - platform: state
        entity_id: sensor.entrancedoor_alarm_level
        to: '255'
      - platform: state
        entity_id: sensor.bedroom_door_alarm_level
        to: '255'
      - platform: state
        entity_id: switch.niskait_magnetkontakt
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm
      - service: notify.pushbullet
        data_template:
          title: 'Alarm triggered'
          message: >
            '{{ trigger.to_state.name }}'
#      - service: notify.pushbullet
#        data_template:
#          title: "Niska@Home! '{{ trigger.to_state.attributes.friendly_name }}'"
#          message: Larm utlöst!
#      - service: notify.html5
#        data_template:
#          title: "Niska@Home! '{{ trigger.to_state.attributes.friendly_name }}'"
#          message: Larm utlöst!

  - alias: 'Alarm Trigger While Armed Home Or Night'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.pirkitchen_alarm_level
        to: '255'
      - platform: state
        entity_id: sensor.smokeniskait_smoke
        to: '255'
      - platform: state
        entity_id: sensor.smokealgots_smoke
        to: '255'
      - platform: state
        entity_id: sensor.smokebedroom_smoke_
        to: '255'
      - platform: state
        entity_id: sensor.smokelivingroom_smoke
        to: '255'
      - platform: state
        entity_id: sensor.smokekitchen_smoke
        to: '255'
      - platform: state
        entity_id: sensor.multisensorbathroom_burglar
        to: '8'
      - platform: state
        entity_id: switch.vardagsrum_magnetkontakt
        to: 'on'
      - platform: state
        entity_id: sensor.entrancedoor_alarm_level
        to: '255'
      - platform: state
        entity_id: sensor.bedroom_door_alarm_level
        to: '255'
      - platform: state
        entity_id: switch.niskait_magnetkontakt
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_night
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm
      - service: notify.pushbullet
        data_template:
          title: 'Alarm triggered'
          message: >
            '{{ trigger.to_state.name }}'
