##################################################
## Customize
##################################################

homeassistant:
#  customize:
google_assistant:
  entity_config:
    light.koksfonster:
      name: Kitchen light
      type: light
      aliases:
        - kitchen
    light.niskait:
      name: office light
      type: light
      aliases:
        - office
    cover.blindsbedroom_level:
      name: Bedroom blinds
      type: switch
      aliases:
        - bedroom shades
        - bedroom covers
        - rullgardin sovrum
    cover.blindsalgots_level:
      name: Algots blind
      type: switch
      aliases:
        - algots shades
    light.algots_fonsterlampa:
      name: Algot window
      type: light
      aliases:
        - algot window light
        - window light algot
    script.goodmorning:
      name: Good morning
      type: switch
      aliases:
        - god morgon
        - morrn
        - morning
    script.goodnight:
      name: Good night
      type: switch
      aliases:
        - night
        - time to sleep
        - god natt
    script.lumos:
      name: Lumos
      type: light
      aliases:
        - lumos
        - light on

##################################################
## Automation
##################################################

automation:
- alias: 'Update Google Assistant on start of Home Assistant'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: google_assistant.request_sync
##################################################
## Script
##################################################

script:
  goodmorning:
    alias: 'God morgon'
    sequence:
    - service: light.turn_on
      entity_id:
        - light.koksfonster
        - light.byran
        - light.algots_fonsterlampa
        - light.office
    - service: cover.open_cover
      entity_id:
        - cover.blindsalgots_level
        - cover.blindsbedroom_level
  goodnight:
    alias: 'Godnatt'
    sequence:
    - service: light.turn_off
      entity_id:
        - light.koksfonster
        - light.vardagsrum
        - light.byran
        - light.algots_fonsterlampa
        - light.iris_matta
        - light.sovrum
        - light.niskait
    - service: cover.close_cover
      entity_id:
        - cover.blindsalgots_level
        - cover.blindsbedroom_level
  lumos:
    alias: 'Lumos'
    sequence:
    - service: light.turn_on
      entity_id:
        - group.all_lights
