# https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/

##################################################
## Customize
##################################################

homeassistant:
  customize:
    sensor.robert_status:
      entity_picture: /local/robert.png
    sensor.tina_status:
      entity_picture: /local/tina.jpg
    group.emilia:
      entity_picture: /local/emilia.jpg
    group.kim:
      entity_picture: /local/kim.jpg
    group.stefan:
      entity_picture: /local/stefan.jpg
    group.elvy:
      entity_picture: /local/elvy.jpg

input_select:
  robert_status_dropdown:
    name: Robert
    options:
      - Hemma
      - Kom nyss hem
      - Lämnade nyss huset
      - Borta
      - Borta längre än 24H

  tina_status_dropdown:
    name: Tina
    options:
      - Hemma
      - Kom nyss hem
      - Lämnade nyss huset
      - Borta
      - Borta längre än 24H

##################################################
## Sensors
##################################################

sensor:
  - platform: template
    sensors:
      robert_status:
        value_template: '{{ states.input_select.robert_status_dropdown.state }}'
        friendly_name: 'Robert'
      tina_status:
        value_template: '{{ states.input_select.tina_status_dropdown.state }}'
        friendly_name: 'Tina'

##################################################
## Group
##################################################
group:
  familj:
    view: no
    name: Familj
    icon: mdi:home-variant
    entities:
      - sensor.robert_status
      - sensor.tina_status
      - group.algot
      - device_tracker.teija_xperia_xz

  guests:
    view: no
    name: Gäster
    icon: mdi:home-variant
    entities:
      - device_tracker.elvys_iphone
      - group.stefan
      - device_tracker.kerstins_honor8
      - device_tracker.pereriks_xperiacompact
      - group.kim
      - group.emilia

  robert:
    name: Robert
    entities:
      - device_tracker.roberts_h8_bt
      - device_tracker.roberts_h8_mac

  tina:
    name: Tina
    entities:
      - device_tracker.tinas_xperia_xz1_compact

  algot:
    name: Algot
    entities:
      - device_tracker.algots_telefon
      - device_tracker.algots_dator

  stefan:
    name: Stefan
    entities:
      - device_tracker.stefans_iphone
      - device_tracker.stefans_iphone_bt

  elvy:
    name: Elvy
    entities:
      - device_tracker.elvysiphone
      - device_tracker.elvysiphone_bt

  emilia:
    name: Emilia
    entities:
      - device_tracker.emiliasiphone
      - device_tracker.emilias_iphone_bt

  kim:
    name: Kim
    entities:
      - device_tracker.joakimsiphone
      - device_tracker.kimsapplewatch

##################################################
## Automations
##################################################

automation:
- alias: Sätt person 'Kom nyss hem'
  trigger:
    - platform: state
      entity_id: group.robert
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: group.tina
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.robert' %}
            input_select.robert_status_dropdown
          {% else %}
            input_select.tina_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'group.robert' %}
            {% if states.input_select.robert_status_dropdown.state == 'Lämnade nyss' %}
              Hemma
            {% else %}
              Kom nyss hem
            {% endif %}
          {% else %}
            {% if states.input_select.tina_status_dropdown.state == 'Lämnade nyss' %}
              Hemma
            {% else %}
              Kom nyss hem
            {% endif %}
          {% endif %}

- alias: Sätt person 'Hemma'
  trigger:
    - platform: state
      entity_id: input_select.robert_status_dropdown
      to: 'Kom nyss hem'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.tina_status_dropdown
      to: 'Kom nyss hem'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.robert_status_dropdown
      from: 'Lämnade nyss huset'
      to: 'Kom nyss hem'
    - platform: state
      entity_id: input_select.tina_status_dropdown
      from: 'Lämnade nyss huset'
      to: 'Kom nyss hem'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.robert_status_dropdown' %}
            input_select.robert_status_dropdown
          {% else %}
            input_select.tina_status_dropdown
          {% endif %}
        option: Hemma

- alias: Sätt person 'Lämnade nyss huset'
  trigger:
    - platform: state
      entity_id: group.robert
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: group.tina
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.robert' %}
            input_select.robert_status_dropdown
          {% else %}
            input_select.tina_status_dropdown
          {% endif %}
        option: Lämnade nyss huset

- alias: Sätt person 'Borta'
  trigger:
    - platform: state
      entity_id: input_select.robert_status_dropdown
      to: 'Lämnade nyss huset'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.tina_status_dropdown
      to: 'Lämnade nyss huset'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.robert_status_dropdown' %}
            input_select.robert_status_dropdown
          {% else %}
            input_select.tina_status_dropdown
          {% endif %}
        option: Borta

- alias: Sätt person 'Borta längre än 24H'
  trigger:
    - platform: state
      entity_id: input_select.robert_status_dropdown
      to: 'Borta'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.tina_status_dropdown
      to: 'Borta'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.robert_status_dropdown' %}
            input_select.robert_status_dropdown
          {% else %}
            input_select.tina_status_dropdown
          {% endif %}
        option: Borta längre än 24H
