# https://github.com/dale3h/homeassistant-config/blob/3a67147a964f093fae209f8ea9ee1759a5421b39/packages/drop-in/secrets_container.yaml

################################################################
## Packages / Secrets Container
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'secrets_container'

      expose: &expose
        <<: *customize
        sensor.secrets:
          expose: false

    ################################################
    ## Sensor
    ################################################

    sensor.secrets:
      <<: *customize
      friendly_name: "Secrets"
      hidden: true
      icon: mdi:file-lock

      secret_of_yours: !secret secret_of_yours
      secret_of_mine: !secret secret_of_mine
      secret_temperatur_nu: !secret temperatur_nu

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      secrets:
        value_template: "Secrets Container"
